Repository 1COMM1T/Camp_us, pull requests merged in 2024-08, with the labels that each got.

#108 Feat: 찜 개수 증감 기능 추가
  src/main/java/com/commit/campus/entity/CampingSummary.java
  src/main/java/com/commit/campus/repository/CampingSummaryRepository.java
  src/main/java/com/commit/campus/service/impl/BookmarkServiceImpl.java
Labels: enhancement

#101 Feature/campings/camping all
  build.gradle
  src/main/java/com/commit/campus/common/config/SwaggerConfig.java
  src/main/java/com/commit/campus/controller/CampingController.java
  src/main/java/com/commit/campus/dto/CampingDTO.java
  src/main/java/com/commit/campus/dto/CampingFacilitiesDTO.java
  src/main/java/com/commit/campus/entity/Camping.java
  src/main/java/com/commit/campus/entity/CampingFacilities.java
  src/main/java/com/commit/campus/repository/CampingRepository.java
  src/main/java/com/commit/campus/service/CampingService.java
  src/main/java/com/commit/campus/service/impl/CampingServiceImpl.java
  src/main/java/com/commit/campus/view/CampingViewModel.java
Labels: enhancement

#116 Feature/review/#110,#111,#112
  build.gradle
  src/main/java/com/commit/campus/common/exceptions/GlobalExceptionHandler.java
  src/main/java/com/commit/campus/common/exceptions/NotAuthorizedException.java
  src/main/java/com/commit/campus/controller/ReviewController.java
  src/main/java/com/commit/campus/dto/CreateReviewRequest.java
  src/main/java/com/commit/campus/dto/ReviewDTO.java
  src/main/java/com/commit/campus/dto/UpdateReviewRequest.java
  src/main/java/com/commit/campus/entity/MyReview.java
  src/main/java/com/commit/campus/repository/RatingSummaryRepository.java
  src/main/java/com/commit/campus/service/ReviewService.java
  src/main/java/com/commit/campus/service/impl/ReviewServiceImpl.java
Labels: enhancement

#134 Feature/review/#130,#131
  src/main/java/com/commit/campus/dto/ReviewDTO.java
  src/main/java/com/commit/campus/entity/CampingSummary.java
  src/main/java/com/commit/campus/entity/MyReview.java
  src/main/java/com/commit/campus/repository/RatingSummaryRepository.java
  src/main/java/com/commit/campus/service/impl/ReviewServiceImpl.java
Labels: enhancement

#153 Feature/admin/#69,#115(관리자기능)
  build.gradle
  src/main/java/com/commit/campus/CampReserveApplication.java
  src/main/java/com/commit/campus/common/config/CognitoWebConfig.java
  src/main/java/com/commit/campus/common/config/JwtUtil.java
  src/main/java/com/commit/campus/common/config/SecurityConfig.java
  src/main/java/com/commit/campus/common/filter/AuthenticationFilter.java
  src/main/java/com/commit/campus/common/filter/JwtFilter.java
  src/main/java/com/commit/campus/controller/AdminController.java
  src/main/java/com/commit/campus/controller/CognitoController.java
  src/main/java/com/commit/campus/controller/OauthController.java
  src/main/java/com/commit/campus/dto/CampingDTO.java
  src/main/java/com/commit/campus/entity/Camping.java
  src/main/java/com/commit/campus/repository/CampingRepository.java
  src/main/java/com/commit/campus/service/AdminService.java
  src/main/java/com/commit/campus/service/CognitoService.java
  src/main/java/com/commit/campus/service/CognitoUserService.java
  src/main/java/com/commit/campus/service/impl/AdminServiceImpl.java
  src/main/java/com/commit/campus/service/impl/CognitoServiceImpl.java
  src/main/java/com/commit/campus/service/impl/CognitoUserServiceImpl.java
  src/main/java/com/commit/campus/service/impl/OauthServiceImpl.java
  src/main/java/com/commit/campus/view/AdminRegisteredCampingView.java
Labels: enhancement

#154 Feature/reservation/#126
  build.gradle
  src/main/java/com/commit/campus/common/config/DynamoDBConfig.java
  src/main/java/com/commit/campus/common/config/LettuceConfig.java
  src/main/java/com/commit/campus/controller/ReservationController.java
  src/main/java/com/commit/campus/dto/ReservationDTO.java
  src/main/java/com/commit/campus/entity/Availability.java
  src/main/java/com/commit/campus/entity/CampingFacilities.java
  src/main/java/com/commit/campus/entity/Reservation.java
  src/main/java/com/commit/campus/entity/User.java
  src/main/java/com/commit/campus/repository/AvailabilityRepository.java
  src/main/java/com/commit/campus/repository/ReservationRepository.java
  src/main/java/com/commit/campus/request/ReservationRequest.java
  src/main/java/com/commit/campus/service/ReservationService.java
  src/main/java/com/commit/campus/service/impl/ReservationServiceImpl.java
  src/main/java/com/commit/campus/view/ReservationView.java
Labels: enhancement, refactor

#147 Feature/review/#144
  src/main/java/com/commit/campus/advice/GlobalExceptionAdvice.java
  src/main/java/com/commit/campus/common/exceptions/ErrorType.java
  src/main/java/com/commit/campus/common/exceptions/GlobalExceptionHandler.java
  src/main/java/com/commit/campus/common/exceptions/NotAuthorizedException.java
  src/main/java/com/commit/campus/common/exceptions/ReviewAlreadyExistsException.java
  src/main/java/com/commit/campus/common/exceptions/ReviewNotFoundException.java
  src/main/java/com/commit/campus/controller/ReviewController.java
  src/main/java/com/commit/campus/dto/ReviewDTO.java
  src/main/java/com/commit/campus/dto/UpdateReviewRequest.java
  src/main/java/com/commit/campus/entity/Review.java
  src/main/java/com/commit/campus/repository/RatingSummaryRepository.java
  src/main/java/com/commit/campus/service/MyReviewService.java
  src/main/java/com/commit/campus/service/ReviewService.java
  src/main/java/com/commit/campus/service/impl/MyReviewServiceImpl.java
  src/main/java/com/commit/campus/service/impl/ReviewServiceImpl.java
  src/main/java/com/commit/campus/view/ErrorView.java
  src/main/java/com/commit/campus/view/MyReviewView.java
  src/main/java/com/commit/campus/view/ReviewView.java
  src/test/java/com/commit/campus/service/MyReviewServiceTests.java
  src/test/java/com/commit/campus/service/ReviewServiceTests.java
Labels: refactor

#170 Feature/reservation/#168
  src/main/java/com/commit/campus/controller/ReservationController.java
  src/main/java/com/commit/campus/dto/ReservationDTO.java
  src/main/java/com/commit/campus/service/ReservationService.java
  src/main/java/com/commit/campus/service/impl/ReservationServiceImpl.java
Labels: enhancement, refactor

#177 Feature/review/#176
  src/main/java/com/commit/campus/common/config/DynamoDBConfig.java
  src/main/java/com/commit/campus/common/config/LettuceConfig.java
  src/main/java/com/commit/campus/service/impl/MyReviewServiceImpl.java
  src/test/java/com/commit/campus/service/MyReviewServiceTests.java
  src/test/java/com/commit/campus/service/ReviewServiceTests.java
Labels: bug, enhancement

#179 Feature/review/#178
  src/main/java/com/commit/campus/controller/MyReviewController.java
  src/main/java/com/commit/campus/controller/ReviewController.java
  src/main/java/com/commit/campus/dto/CreateReviewRequest.java
  src/main/java/com/commit/campus/dto/ReviewDTO.java
  src/main/java/com/commit/campus/dto/UpdateReviewRequest.java
  src/test/java/com/commit/campus/service/ReviewServiceTests.java
Labels: refactor

#181 fix: userId 조회 실패 문제 해결
  src/main/java/com/commit/campus/repository/UserRepository.java
Labels: bug

#184 Feature/infra/#182
  .github/workflows/deploy.yml
  .gitignore
  src/main/resources/application.yml
Labels: enhancement

#186 Feat: gradle wrapper 파일들 등록
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: bug
